### PR TITLE
[Bugfix] Fix total KPIs for arbitrary date ranges

### LINKED ISSUE #37: [Bug] KPIs not updating when time range is other than last 7 days
### Module

Dashboard

### Describe the Bug

The general KPIs are showing wrong information when the filtered time range is different than the default (last 7 days).

This is because the dashboard is querying the `kpi` endpoint, but not passing the dates in a way they can be used.

image

The endpoint accepts parameters on the endpoint, but not specifying them in the `where` clause.

image

### Expected Behavior

KPIs information is right for the selected time period.

### To Reproduce

Filter any other time range different than "last 7 days". For example in this example the rest of the use cases show data for the specified time period, but the KPIs don't.

image

image

### Details

_No response_

### PR DESCRIPTION
**Pull request by alejandromav**
# Description

Fixes #37

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

# How Has This Been Tested?

Tested in localhost using actual data.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have update the [CHANGELOG](https://github.com/tinybirdco/web-analytics-starter-kit/blob/main/CHANGELOG.md)
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: dashboard/lib/hooks/use-kpi-totals.ts [hunk 1]
```diff
@@ -8,42 +8,44 @@ async function getKpiTotals(
...
 
   return {
-    avg_session_sec: avg_session_sec,
-    pageviews: pageviews,
-    visits: visits,
-    bounce_rate: bounce_rate,
+    avg_session_sec: _ponderatedKPIsTotal('avg_session_sec'),
+    pageviews: KPITotal('pageviews'),
+    visits: totalVisits,
+    bounce_rate: _ponderatedKPIsTotal('bounce_rate')
```
Comment (alejandromav) [inline dashboard/lib/hooks/use-kpi-totals.ts:48]: @rmorehig not 100% convinced about this.

Any thoughts, or better solution?

**Review by rmorehig — APPROVED** [review]

**Review by rmorehig — APPROVED** [review]
